language: scala
sudo: false
scala:
  - 2.11.8
jdk:
  - openjdk7
  - oraclejdk7
  - oraclejdk8
script:
  - sbt ++$TRAVIS_SCALA_VERSION clean coverage test coverageReport
  - sbt ++$TRAVIS_SCALA_VERSION coverageAggregate
after_success:
  - bash <(curl -s https://codecov.io/bash)
